### ISSUE TITLE
Missing keyword 'action' argument error 

### ISSUE THREAD

**Issue by Soonmok** [youknowone/ring#36]
```python
import ring
import redis

cache_dict = {}

@ring.func.dict(cache_dict)
def test(a):
    return a + 3

@ring.func.dict(cache_dict)
def test2(a):
    return a +4

print(test(3))
print(test2(3))
```

```
Traceback (most recent call last):
  File "/home/spark/.pyenv/plugins/pyenv-virtualenv/ring/keyCollision.py", line 1, in <module>
    import ring
  File "/home/spark/.pyenv/plugins/pyenv-virtualenv/ring/ring/__init__.py", line 2, in <module>
    import ring.func  # noqa
  File "/home/spark/.pyenv/plugins/pyenv-virtualenv/ring/ring/func.py", line 3, in <module>
    from ring.func_sync import dict  # noqa
  File "/home/spark/.pyenv/plugins/pyenv-virtualenv/ring/ring/func_sync.py", line 6, in <module>
    from ring import func_base as fbase
  File "/home/spark/.pyenv/plugins/pyenv-virtualenv/ring/ring/func_base.py", line 199
    raise TypeError("run() missing 1 required keyword argument: 'action'") from exc
                                                                              ^
SyntaxError: invalid syntax
```

**Comment by yunitto** [comment]
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import ring
  File "/ring/__init__.py", line 2, in <module>
    import ring.func  # noqa
  File "/ring/func.py", line 3, in <module>
    from ring.func_sync import dict  # noqa
  File "/ring/func_sync.py", line 6, in <module>
    from ring import func_base as fbase
  File "/ring/func_base.py", line 199
    raise TypeError("run() missing 1 required keyword argument: 'action'") from exc
                                                                              ^
```
python2로 실행하면 from부분에서 syntax error가 나는 것 같습니다. python3로 실행하면 일단 돌아갑니다.

**Comment by yunitto** [comment]
python2에서도 돌아가게 하려면 기존의

```
raise TypeError("run() missing 1 required keyword argument: 'action'") from exc
```
를 다음과 같이 바꾸면 될 것 같습니다.
```
raise_from(TypeError("run() missing 1 required keyword argument: 'action'"), exc)
```

[stackoverflow](https://stackoverflow.com/questions/34463087/raise-exception-in-python-2-x-and-3-x) 를 참고했습니다.

**Comment by youknowone** [comment]
Fixed in #38
